### ISSUE TITLE
Remove User Column

### ISSUE THREAD

**Issue by ZAID-0196** [Shadbox-Infosystem/hr-shadbox#28]
Remove user column in attendance sheet.

![Image](https://github.com/Shadbox-Infosystem/hr-shadbox/assets/163137146/ed23d313-6bdb-4556-919e-5ee3936c3eaf)

**Comment by asad-fazlani** [comment]
@RushikeshGhurde add MR link in comment
@Akram-8888 @ZAID-0196

**Comment by ZAID-0196** [comment]
**PR link:** https://github.com/Shadbox-Infosystem/hr-shadbox/pull/44

**Comment by asad-fazlani** [comment]
@Abdul-Kalam87 move this to prod as well

**Comment by Abdul-Kalam87** [comment]
@asad-fazlani moved to prod now.
