### ISSUE TITLE
Change default email

### ISSUE THREAD

**Issue by ZAID-0196** [Shadbox-Infosystem/hr-shadbox#35]
1) change email form hr@shadbox.com to support@shadbox.com.
2) reindent some code.

**Comment by Abdul-Kalam87** [comment]
this is done and merged.


![Image](https://github.com/Shadbox-Infosystem/hr-shadbox/assets/115706070/43586412-e57d-43d9-827e-036d92215aa0)

cc: @asad-fazlani @shahnawaz-ror @ahmadadnan1602

**Comment by asad-fazlani** [comment]
Thanks @Abdul-Kalam87
